auth_enabled: false

server:
  http_listen_port: 3100
  # Écouter sur toutes les interfaces dans le conteneur
  http_listen_address: 0.0.0.0

# La configuration des chemins internes au conteneur
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  ring:
    kvstore:
      store: inmemory

# Limites adaptées pour un environnement de développement
limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_stream_rate_limit: 10MB
  max_entries_limit_per_query: 10000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false

# Configuration des schémas de stockage
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Configuration du stockage adaptée aux chemins dans le conteneur
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks

# Configuration de l'ingester
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: /loki/wal

# Configuration du compacteur
compactor:
  working_directory: /loki/compactor