spring:
  application:
    name: user-manager

  # Database Configuration
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:your-secret-key-with-at-least-32-characters}
      encryption-key: ${JWT_ENCRYPTION_KEY:your-encryption-key-with-at-least-32-characters}
      expire-length-ms: ${JWT_EXPIRE_LENGTH:3600000}  # 1 heure
      refresh-expire-length-ms: ${JWT_REFRESH_EXPIRE_LENGTH:604800000}  # 7 jours
  brute-force-protection:
    enabled: true
    ip-max-attempts: 10
    username-max-attempts: 5
    session-max-attempts: 3
    initial-block-duration-minutes: 5
    max-block-duration-hours: 24
    block-multiplier: 2
  headers:
    content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self'"
    referrer-policy: "strict-origin-when-cross-origin"
    feature-policy: "camera 'none'; microphone 'none'; geolocation 'none'; payment 'none'"
    permissions-policy: "camera=(), microphone=(), geolocation=(), payment=()"


# Server Configuration
server:
  port: 8080

# Configuration OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
  show-actuator: true
  packages-to-scan: fr.lpreaux.usermanager.infrastructure.adapter.in.web
  paths-to-match: /api/**

sentry:
  dsn: https://baa699b68b71d63aecdef55f352eeed0@o4509312009109504.ingest.de.sentry.io/4509312013303888  # Obtenez ce DSN depuis votre compte Sentry
  traces-sample-rate: 1.0
  environment: undefined
  release: ${project.name}@${project.version}
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info

management:
  info:
    env:
      enabled: true
    git:
      mode: full
  prometheus:
    metrics:
      export:
        enabled: true

# Configuration PostHog
posthog:
  api-key: ${POSTHOG_API_KEY}
  host: ${POSTHOG_HOST}
  enabled: ${POSTHOG_ENABLED:true}
  environment: undefined
