version: 2.1

orbs:
  codecov: codecov/codecov@5.3.0

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:23.0
      - image: cimg/mariadb:11.0
        environment:
          MYSQL_DATABASE: user_manager_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: root_password
    working_directory: ~/user-manager

jobs:
  build-and-test:
    executor: java-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Download Dependencies
          command: ./mvnw dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Run Tests with Coverage
          command: |
            ./mvnw clean test \
              -Dspring.profiles.active=test
          environment:
            MAVEN_OPTS: -Xmx3200m

      - run:
          name: Generate Coverage Report
          command: ./mvnw jacoco:report

      - run:
          name: Check Coverage
          command: ./mvnw jacoco:check@jacoco-check || true

      - run:
          name: Run Integration Tests
          command: |
            ./mvnw verify \
              -Dspring.profiles.active=test \
              -DskipTests

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/site/jacoco
          destination: coverage

      # Upload vers Codecov (pour GitLab)
      - codecov/upload:
          files: target/site/jacoco/jacoco.xml
          flags: unittests
          upload_name: user-manager-coverage

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test