# CircleCI configuration for User Manager project
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
  
executors:
  java-executor:
    docker:
      - image: cimg/openjdk:23.0
      - image: cimg/mariadb:11.0
        environment:
          MYSQL_DATABASE: user_manager_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: root_password
    working_directory: ~/user-manager

jobs:
  build-and-test:
    executor: java-executor
    steps:
      - checkout
      
      # Restore cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      
      # Download dependencies
      - run:
          name: Download Dependencies
          command: ./mvnw dependency:go-offline
      
      # Save dependencies to cache
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      
      # Wait for database
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      
      # Build the application
      - run:
          name: Build
          command: ./mvnw clean compile
      
      # Run unit tests
      - run:
          name: Run Unit Tests
          command: |
            ./mvnw test \
              -Dspring.profiles.active=test \
              -Dspring.datasource.url=jdbc:mariadb://localhost:3306/user_manager_test \
              -Dspring.datasource.username=test_user \
              -Dspring.datasource.password=test_password
          environment:
            MAVEN_OPTS: -Xmx3200m
      
      # Run integration tests
      - run:
          name: Run Integration Tests
          command: |
            ./mvnw verify \
              -Dspring.profiles.active=test \
              -DskipUnitTests
      
      # Generate coverage report
      - run:
          name: Generate Coverage Report
          command: ./mvnw jacoco:report
      
      # Store test results
      - store_test_results:
          path: target/surefire-reports
      
      # Store artifacts
      - store_artifacts:
          path: target/site/jacoco
          destination: coverage
      
      # Upload coverage to Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      
      # SonarCloud analysis (optional)
      # - run:
      #   name: SonarCloud Analysis
      #    command: |
      #      if [ -n "$SONAR_TOKEN" ]; then
      #       ./mvnw sonar:sonar \
      #         -Dsonar.projectKey=your-project-key \
      #         -Dsonar.organization=your-org \
      #         -Dsonar.host.url=https://sonarcloud.io \
      #         -Dsonar.login=$SONAR_TOKEN
      #     fi

  build-docker:
    executor: java-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker Image
          command: |
            docker build -t user-manager:${CIRCLE_SHA1} .
      - run:
          name: Run Docker Container Tests
          command: |
            docker-compose -f docker-compose.test.yml up --abort-on-container-exit

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - build-docker:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
